{
 "title": "SmartWellness",
 "time": { "from": "now-2h", "to": "now" },
 "panels": [
  {
   "title": "Gym temperature sensor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,1m,0),\n  sensorType AS metric,\n  avg(value) AS \"value\"\nFROM DataSamples\nWHERE\n  $__timeFilter(timestamp) AND\n  node = 2\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,1m,0)"
    }
   ]
  },
  {
   "title": "Gym Crepuscular sensor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,1m,0),\n  sensorType AS metric,\n  avg(value) AS \"value\"\nFROM DataSamples\nWHERE\n  $__timeFilter(timestamp) AND\n  node = 3\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,1m,0)"
    }
   ]
  },
  {
   "title": "Gym: Manual",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,1m,0),\n  sensorType AS metric,\n  avg(manual) AS \"manual\"\nFROM DataSamples\nWHERE\n  $__timeFilter(timestamp) AND\n  node = 2 OR\n  node = 3\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,1m,0)"
    }
   ]
  },
  {
   "title": "Steam Bath Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,1m,0),\n  sensorType AS metric,\n  avg(value) AS \"value\"\nFROM DataSamples\nWHERE\n  $__timeFilter(timestamp) AND\n  node = 4\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,1m,0)"
    }
   ]
  },
  {
   "title": "Steam Bath Presence Sensor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,1m,0),\n  sensorType AS metric,\n  avg(value) AS \"value\"\nFROM DataSamples\nWHERE\n  $__timeFilter(timestamp) AND\n  node = 5\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,1m,0)"
    }
   ]
  },
  {
   "title": "Steam Bath: Manual",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,1m,0),\n  sensorType AS metric,\n  avg(manual) AS \"manual\"\nFROM DataSamples\nWHERE\n  $__timeFilter(timestamp) AND\n  node = 4 OR\n  node = 5\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,1m,0)"
    }
   ]
  },
  {
   "title": "Pool pH",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,1m,0),\n  sensorType AS metric,\n  avg(value) AS \"value\"\nFROM DataSamples\nWHERE\n  $__timeFilter(timestamp) AND\n  node = 6\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,1m,0)"
    }
   ]
  },
  {
   "title": "Pool Chlorine",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,1m,0),\n  sensorType AS metric,\n  avg(value) AS \"value\"\nFROM DataSamples\nWHERE\n  $__timeFilter(timestamp) AND\n  node = 7\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,1m,0)"
    }
   ]
  },
  {
   "title": "Pool: Manual",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,1m,0),\n  sensorType AS metric,\n  avg(manual) AS \"manual\"\nFROM DataSamples\nWHERE\n  $__timeFilter(timestamp) AND\n  node = 6 OR\n  node = 7\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,1m,0)"
    }
   ]
  }
 ]
}