{
 "title": "SmartWellness",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Gym temperature sensor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,1m,0),\n  sensorType AS metric,\n  avg(value) AS \"value\"\nFROM DataSamples\nWHERE\n  $__timeFilter(timestamp) AND\n  sensorType = \"tempSensor\"\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,1m,0)"
    }
   ]
  },
  {
   "title": "Gym Crepuscular sensor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,1m,0),\n  sensorType AS metric,\n  avg(value) AS \"value\"\nFROM DataSamples\nWHERE\n  $__timeFilter(timestamp) AND\n  sensorType = \"crepuscularSensor\"\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,1m,0)"
    }
   ]
  },
  {
   "title": "Gym: Manual",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  sensorType AS metric,\n  manual\nFROM DataSamples\nWHERE\n  $__timeFilter(timestamp) AND\n  sensorType = \"tempSensor\" OR\n  sensorType = \"crepuscularSensor\"\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Steam Bath Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,1m,0),\n  sensorType AS metric,\n  avg(value) AS \"value\"\nFROM DataSamples\nWHERE\n  $__timeFilter(timestamp) AND\n  sensorType = \"humiditySensor\"\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,1m,0)"
    }
   ]
  },
  {
   "title": "Steam Bath Presence Sensor",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,1s),\n  sensorType AS metric,\n  avg(value) AS \"value\"\nFROM DataSamples\nWHERE\n  $__timeFilter(timestamp) AND\n  sensorType = \"presenceSensor\"\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,1s)"
    }
   ]
  },
  {
   "title": "Steam Bath: Manual",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  sensorType AS metric,\n  manual\nFROM DataSamples\nWHERE\n  $__timeFilter(timestamp) AND\n  sensorType = \"humiditySensor\" OR\n  sensorType = \"presenceSensor\"\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Pool pH",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,1m,0),\n  sensorType AS metric,\n  avg(value) AS \"value\"\nFROM DataSamples\nWHERE\n  $__timeFilter(timestamp) AND\n  sensorType = \"phSensor\"\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,1m,0)"
    }
   ]
  },
  {
   "title": "Pool Chlorine",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,1m,0),\n  sensorType AS metric,\n  avg(value) AS \"value\"\nFROM DataSamples\nWHERE\n  $__timeFilter(timestamp) AND\n  sensorType = \"chlorineSensor\"\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,1m,0)"
    }
   ]
  },
  {
   "title": "Pool: Manual",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  sensorType AS metric,\n  manual\nFROM DataSamples\nWHERE\n  $__timeFilter(timestamp) AND\n  sensorType = \"chlorineSensor\" OR\n  sensorType = \"phSensor\"\nORDER BY timestamp"
    }
   ]
  }
 ]
}